# Generated by Django 4.0.6 on 2022-07-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(default='untitled', max_length=25),
        ),
    ]
